config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: [:index,:create]
  resources :smoothies
  # get 'ingredients/show'
  # get 'ingredients/new'
  # get 'ingredients/edit'
  # get 'smoothies/index'
  # get 'smoothies/show'
  # get 'smoothies/new'
  # get 'smoothies/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipes
    has_many :smoothies, through: :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :smoothie
    belongs_to :ingredient
end

app/models/smoothie.rb
class Smoothie < ApplicationRecord
    has_many :recipes
    has_many :ingredients, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController
  def index
    @smoothies = Smoothie.all
  end

  def show
    @smoothie = Smoothie.find(params[:id]) 
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/smoothies_helper.rb
module SmoothiesHelper
end

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<p><% @ingredients.each do |ingredient|%>
<%= puts ingredient.name%> 
<% end %>
</p>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RootyTootyBlendyFruity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/smoothies/edit.html.erb
<h1>Smoothies#edit</h1>
<p>Find me in app/views/smoothies/edit.html.erb</p>

app/views/smoothies/index.html.erb
<h1>Smoothies</h1>
<p><% @smoothies.each do |smoothie|%>
<%= link_to smoothie.name, smoothy_path(smoothie)%> 
<% end %>

app/views/smoothies/new.html.erb
<h1>Smoothies#new</h1>
<p>Find me in app/views/smoothies/new.html.erb</p>

app/views/smoothies/show.html.erb
<h1><%=@smoothie.name%></h1>
<p><% @smoothie.ingredients.each do |ingredient|%>
<%= "* " + ingredient.name%>
<%end%>
</p>